<?php if($this->stronicowanieStrony->currentItemCount > 0) { ?>
 
  
   <?php 
    $lp = 1; 
    foreach($this->all as $entityObject) :
   ?>

    <div class="panel panel-default">
        
        <?php
            echo $this->escapeHtml($entityObject->getId()).' | '.$this->escapeHtml($entityObject->getData()->format('d.m.Y H:i')).' - '.$this->escapeHtml($entityObject->getDataKoniec()->format('d.m.Y H:i')).' | '.$this->escapeHtml($entityObject->getPacjent()->getPesel()).' | '.$this->escapeHtml($entityObject->getLekarz()->getLid());
        ?>
        
    </div>
    
   <?php
    endforeach;
    
    /*$tmpData1 = new \DateTime(date('Y-m-d', time()).' 23:59:59');
    $tmpData2 = new \DateTime(date('Y-m-d', time()+86400*3).' 00:00:00');
    echo 'D1: '.$tmpData1->format('d.m.Y H:i:s').'<br />';
    echo 'D2: '.$tmpData2->format('d.m.Y H:i:s').'<br />';
    echo 'R: '. floor((((int)$tmpData2->format('U')) - ((int)$tmpData1->format('U'))-1)/86400);*/
   ?>
   
<?php echo $this->partial('partial/paginacja_part', array(
    'stronicowanieStrony' => $this->stronicowanieStrony)); ?>
 

<?php 
    } else { 
        echo '<div class="alert alert-warning">Brak danych do wyświetlenia.</div>';
    } 
?>