<?php if($this->stronicowanieStrony->currentItemCount > 0) { ?>
 
  
   <?php 
    $lp = 1; 
    foreach($this->all as $entityObject) :
   ?>

    <div class="panel panel-default" style="padding: 10px 5px;">
        
        <?php
            if($entityObject->getStatus() == 0){
                $statAlertCSS = 'success';
                $statPrzezKogo = '';
                
                if($entityObject->getPacjent()->getId() == 1) $statAlertCSS = 'info';
                
            } else if($entityObject->getStatus() == 1){
                $statAlertCSS = 'danger';
                $statPrzezKogo = '<small><i>odwołana przez pacjenta</i></small>';
            } else if($entityObject->getStatus() == 2){
                $statAlertCSS = 'danger';
                $statPrzezKogo = '<small><i>odwołana przez lekarza</i></small>';
            } 
            echo '<span class="alert alert-'.$statAlertCSS.'" style="font-size: 14px;">'.$this->escapeHtml($entityObject->getData()->format('H:i d.m.Y')).' - '.$this->escapeHtml($entityObject->getDataKoniec()->format('H:i d.m.Y')).'</span> '.$statPrzezKogo;
            
             if($entityObject->getStatus() == 0 && $this->identity()->poziom != 2) {
        ?>
                
          <a href="<?php echo $this->url($this->route, array('id' => $this->escapeHtml($entityObject->getId()), 'action' => 'odwolaj')); ?>" class="btn btn-warning btn-xs">
            Odwołaj wizytę
          </a>
          
        <?php
            } else if($entityObject->getStatus() == 0) {
        ?>
           
        <div class="btn-group text-left" style="margin-top: 0px;">
          <a class="btn btn-warning btn-xs dropdown-toggle" data-toggle="dropdown">
            Odwołaj wizytę <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <?php
               echo '<li><a href="'.($this->url($this->route, array('did'=>1, 'id' => $this->escapeHtml($entityObject->getId()), 'action' => 'odwolaj'))).'">jako lekarz</a></li>';
               echo '<li><a href="'.($this->url($this->route, array('did'=>0, 'id' => $this->escapeHtml($entityObject->getId()), 'action' => 'odwolaj'))).'">jako pacjent</a></li>';               
            ?>
          </ul>
        </div>
        
        <?php
            }
            
            if($this->identity()->poziom == 2){
                echo ' <a href="'.$this->url($this->route, array('id' => $this->escapeHtml($entityObject->getId()), 'action' => 'usun')).'" class="btn btn-danger btn-xs">
                Usuń wizytę
              </a> ';
            }
            
            if($entityObject->getPacjent()->getId() != 1){
                echo ' <h3><small>Pacjent:</small> '.$this->escapeHtml($entityObject->getPacjent()->getImie()).' '.$this->escapeHtml($entityObject->getPacjent()->getNazwisko());
            } else {
                echo ' <h3>URLOP';
            }
            
            echo ' <span style="margin-left: 35px"><small>Lekarz:</small> '.$this->escapeHtml($entityObject->getLekarz()->getTytulNaukowy().' '.$entityObject->getLekarz()->getImie()).' '.$this->escapeHtml($entityObject->getLekarz()->getNazwisko()).'</span></h3>';
            
            
        ?>
        
    </div>
    
   <?php
    endforeach;
    
   
   ?>
   
<?php echo $this->partial('partial/paginacja_part', array(
    'stronicowanieStrony' => $this->stronicowanieStrony)); ?>
 

<?php 
    } else { 
        echo '<div class="alert alert-warning">Brak danych do wyświetlenia.</div>';
    } 
?>