<?php if($this->stronicowanieStrony->currentItemCount > 0) { ?>
 
  
   <?php 
    $lp = 1; 
    foreach($this->all as $entityObject) :
   ?>

    <div class="panel panel-default">
        <table class="table table-bordered">
        <tr>
           <td>
           <h3 style="margin-top: 8px; margin-bottom: 8px;"><small>
              <?php 
                echo $this->escapeHtml($entityObject->getTytulNaukowy()).'</small> '.$this->escapeHtml($entityObject->getImie().' '.$entityObject->getNazwisko()); 
                if($this->identity() && ($this->identity()->poziom == 2 || $this->identity()->id == $entityObject->getId())) echo ' <a href="'.$this->url('lekarz', array('action' => 'edytuj', 'id' => $this->escapeHtml($entityObject->getLid()))).'" title="" class="btn btn-danger btn-xs">Edytuj</a> 
                <a href="'.$this->url('lekarz', array('action' => 'usun', 'id' => $this->escapeHtml($entityObject->getLid()))).'" title="" class="btn btn-warning btn-xs">Usuń</a>';
              ?>
              <br /><small><em><?php echo $this->escapeHtml($entityObject->getSpec()->getNazwa()); ?></em></small>
            </h3>
            </td>
            <td style="vertical-align: middle; width: 320px;">
                <?php if(!($this->identity()->poziom == 1 && $entityObject->getId() == $this->identity()->id)) { ?>
                <a href="<?php echo $this->url('wizyta', array('controller' => 'rejestracja', 'action' => 'zapiszSie')); ?>" class="btn btn-success" title="">Zarejestruj się na wizytę!</a> 
                <?php } ?>
                <span class="btn btn-info grafik-open" data-toggle="popover" title="" data-content="<?php echo $this->escapeHtml($this->partial('partial/grafik_lekarza', array('grafik'=>$entityObject->getGrafikArray(), 'lekarz_id' =>$entityObject->getLid()))); ?>" role="button" data-placement="left" data-original-title="Ogólny grafik pracy">Zobacz grafik</span> 
            </td>
        </tr>
        </table>
    </div>
    
   <?php
    endforeach;
   ?>
   
<?php echo $this->partial('partial/paginacja_part', array(
    'stronicowanieStrony' => $this->stronicowanieStrony)); ?>
 

<?php 
    } else { 
        echo '<div class="alert alert-warning">Brak danych do wyświetlenia.</div>';
    } 
?>