<?php echo $this->doctype(); ?>

<html lang="pl">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Wirtualna Przychodnia')->setSeparator(' :: ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style_custom.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                                    ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <div class="naglowek">
        <header class="main">

            <nav class="navbar" role="navigation">
                
                <ul class="nav nav-pills">
                  <li><a href="<?php echo $this->url('home') ?>">Strona główna</a></li>
                  
                  <?php 
                    $user = $this->identity();
                    
                    if(!$user) // niezalogowany
                    {
                    ?>
                  
                  <li><a href="<?php echo $this->url('home') ?>">Rejestracja</a></li>
                  <li><a href="<?php echo $this->url('uzytkownik', array('controller'=>'logowanie')) ?>">Logowanie</a></li>
                  
                  <?php
                    } else if(($poziomUzytkownika = intval($user->poziom)) === 0){ // pacjent
                   ?>
                  <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Panel Pacjenta<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                  <li><a href="<?php echo $this->url('wizyta', array('controller' => 'index')); ?>">Moje wizyty</a></li>
                                  <li><a href="#">Zapisz się na wizytę</a></li>
                                  <li><a href="#">Znajdź lekarza</a></li>
                                  <li class="divider"></li>
                                  <li><a href="<?php echo $this->url('uzytkownik', array('controller' => 'profil')); ?>">Mój profil</a></li>

                                </ul>
                  </li>
                  
                  <?php
                    } else if ($poziomUzytkownika === 1){ // lekarz
                    ?>
                  <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Panel Lekarza<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                  <li><a href="<?php echo $this->url('wizyta', array('controller' => 'index')); ?>">Moje wizyty</a></li>
                                  <li><a href="<?php echo $this->url('lekarz', array('controller' => 'profil', 'action' => 'dodaj')); ?>">Dodaj specjalność</a></li>
                                  
                                  <li><a href="<?php echo $this->url('lekarz', array('controller' => 'profil', 'action' => 'moje-specjalnosci')); ?>">Moje specjalności</a></li>
                                  <li class="divider"></li>
                                  <li><a href="<?php echo $this->url('lekarz', array('controller' => 'profil', 'action' => 'zaznacz-urlop')); ?>">Zaznacz nieobecność</a></li>
                                  <li class="divider"></li>
                                  <li><a href="<?php echo $this->url('uzytkownik', array('controller' => 'profil')); ?>">Mój profil</a></li>
                           
                                </ul>
                  </li>
                  
                  <?php
                    } else if ($poziomUzytkownika === 2){ // administracja
                  ?>
                    <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Panel Recepcjonisty<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                  <li><a href="<?php echo $this->url('uzytkownik', array('action' => 'index')); ?>">Użytkownicy</a></li>
                                  <li><a href="<?php echo $this->url('wizyta', array('controller' => 'index')); ?>">Wizyty</a></li>
                                  <li class="divider"></li>
                                  <li><a href="<?php echo $this->url('lekarz', array('action' => 'edytuj', 'id' => 0)); ?>">Dodaj lekarza</a></li>
                                  <li><a href="<?php echo $this->url('lekarz'); ?>">Lekarze</a></li>
                                  <li class="divider"></li>
                                  <li><a href="#">Dodaj pacjenta</a></li>
                                  <li><a href="#">Pacjenci</a></li>
                                  <li class="divider"></li>
                                  <li><a href="<?php echo $this->url('uzytkownik', array('controller' => 'profil')); ?>">Mój profil</a></li>
                              </ul>
                    </li>
                  
                  <?php
                    }
                  ?>
                  
                  <li><a href="<?php echo $this->url('kontakt') ?>">Kontakt</a></li>
                  
                  <?php
                    if($user){
                     echo '<li><a href="'.($this->url('uzytkownik', array('controller' => 'logowanie', 'action' => 'wyloguj'))).'">Wyloguj</a></li>';
                    }
                  ?>
                </ul>
            </nav>
        </header>
    </div>
        
        <div class="container szary_piasek">
            <div class="miejsce_na_tresc">
            <?php echo $this->content; ?>
            </div>

        </div> <!-- /container -->
        
        <footer>
                <p>Projekt wykonany na potrzeby przedmiotu "Projekt zespołowy"<br />
                Zespół w składzie: Darek Jędrzejka, Grzegorz Szamburski<br />
                2013</p>
        </footer>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
