<h1>Skontaktuj się z nami!</h1>
<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Dane teleadresowe</h3>
        </div>
        <div class="panel-body">
            <h4>NZOZ Wirtualny</h4>
            <p>ul. Banacha<br />
                90-238 Łódź</p>
            <p>tel. 042 600-00-00<br />
               fax. 042 600-00-01<br />
               e-mail: recepcja@nzozwirutalny.pl</p>
            <p>Godziny pracy:<br />
            pn. - pt. 7:00 - 19:00<br />
            sb. - nd. 8:00 - 16:00                        
            </p>
        </div>
    </div>
</div>

<div class="col-md-8">
<iframe class="img-thumbnail" style="width: 670px; height: 350px;" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.pl/maps?q=51.776543,19.487004&amp;num=1&amp;ie=UTF8&amp;t=m&amp;ll=51.776497,19.486742&amp;spn=0.018587,0.057507&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.pl/maps?q=51.776543,19.487004&amp;num=1&amp;ie=UTF8&amp;t=m&amp;ll=51.776497,19.486742&amp;spn=0.018587,0.057507&amp;z=14&amp;source=embed" style="color:#0000FF;text-align:left">Wyświetl większą mapę</a></small>
</div>
