<?php 
    if(isset($this->result))
    {
        if($this->result->getCode() > 0){ $messageStyle = 'alert-success'; }
        else { $messageStyle = 'alert-danger'; }
        
        echo '<div class="alert '.$messageStyle.'">';
        foreach($this->result->getMessages() as $msg){
            echo $this->translate($this->escapeHtml($msg)).'<br />';
        }
        echo '</div>';
    } else if(isset($this->pokazKomunikat) && $this->pokazKomunikat){
        echo '<div class="alert alert-warning">Dostęp do tej części strony wymaga zalogowania. Nie masz konta? <a href="'.$this->url('uzytkownik', array('controller' => 'rejestracja')).'">Zarejestruj się</a></div>';
    }
    

    $tytul = 'Logowanie';
    $this->headTitle($tytul);
    
    

    
    if ($user = $this->identity()) {
        echo '<div class="row">
        <div class="alert alert-success col-md-6 col-md-offset-3 text-center"><strong>Użytkownik zalogowany</strong><br />'. $this->escapeHtml($user->imie . ' ' . $user->nazwisko . ' (' . $user->email . ')') .'</div>
        </div>
        <div class="row">
        <a href="'.($this->url('uzytkownik', array('controller' => 'logowanie', 'action' => 'wyloguj'))).'" title="" class="btn btn-info col-md-2 col-md-offset-5 text-center"><strong>WYLOGUJ</strong></a>
        </div>
        ';
?>		


<?php
    } else { 
 echo '<h3 style="margin: 10px auto; width: 170px;">'.$tytul.'</h3>';
 
$form = $this->form;

$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
<div class="col-md-offset-5 col-md-4">


<div class="row">
<div class="form-group col-md-10">
      <?php echo $this->formRow($form->get('pesel')); ?>
  </div>
</div>  
<div class="row">
  <div class="form-group col-md-10">

      <?php echo $this->formRow($form->get('haslo')); ?>

  </div>
</div> 
<div class="row">
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <div class="checkbox">
        <?php echo $this->formRow($form->get('rememberme')); ?>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-md-offset-3 col-md-4">
      <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
  </div>
</div> 

</div>
</div>

<?php echo $this->form()->closeTag();   


    }
?>
