<?php

 $title = 'Moje specjalności';
 $this->headTitle($title);
 $this->headScript()->appendScript('
    $(document).ready(function (){
        $(".tooltip-btn").mouseover(function (e){
            $(this).tooltip(\'show\');
        });
        
        $(".tooltip-btn").mouseout(function (e){
            $(this).tooltip(\'hide\');
        });
        
         $(".grafik-open").popover({ html : true});
        
        $(".grafik-open").mouseover(function (e){
            $(this).popover(\'show\');
        });
        
        $(".grafik-open").mouseout(function (e){
            $(this).popover(\'hide\');
        });
    });
 ');
 
 
 ?>
 
<div class="row">
     <div class="col-md-9">
        <h1 style="margin-top: 5px;">
        <?php 
            echo $this->escapeHtml($title); 
        ?>    
        </h1>
     </div>
    <div class="col-md-3 text-right">
        <div class="btn-group text-left" style="margin-top: 5px;">
          <a href="<?php echo $this->url('lekarz', array('controller'=>'profil', 'action'=>'edytuj')); ?>" class="btn btn-primary" >
            <span class="glyphicon glyphicon-plus-sign"></span>
             Dodaj specjalność
          </a>

        </div>
    </div>
</div>


 
<?php 
    echo $this->partial('partial/lista_lekarzy', array('stronicowanieStrony' => $this->stronicowanieStrony, 'all' => $this->all));
?>