<?php

 $title = 'Wszyscy użytkownicy';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('uzytkownik', array('action'=>'dodaj'));?>">Dodaj użytkownika</a>
 </p>

 <table class="table">
 <tr>
     <th>Imię</th>
     <th>Nazwisko</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($user->imie);?></td>
     <td><?php echo $this->escapeHtml($user->nazwisko);?></td>
     <td>
         <a href="<?php echo $this->url('uzytkownik',
             array('controller'=>'index', 'action'=>'edytuj', 'id' => $user->id));?>">Zmień</a>
         <a href="<?php echo $this->url('uzytkownik',
             array('controller'=>'index', 'action'=>'usun', 'id' => $user->id));?>">Usuń</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>