<?php

 $title = 'Rejestracja na wizytę';
 $this->headTitle($title);
 $this->headScript()->appendScript('
    $(document).ready(function (){
        $(".tooltip-btn").mouseover(function (e){
            $(this).tooltip(\'show\');
        });
        
        $(".tooltip-btn").mouseout(function (e){
            $(this).tooltip(\'hide\');
        });
        
         $(".grafik-open").popover({ html : true});
        
        $(".grafik-open").mouseover(function (e){
            $(this).popover(\'show\');
        });
        
        $(".grafik-open").mouseout(function (e){
            $(this).popover(\'hide\');
        });
    });
 ');
 
 
 ?>
 <div class="row">
     <div class="col-md-9">
        <h1 style="margin-top: 5px;">
        <?php 
            echo $this->escapeHtml($title); 
        ?>    
        </h1>
     </div>
    <div class="col-md-3 text-right">
       <?php echo $this->escapeHtml(' ');  ?>
    </div>
</div>

<?php
    if($this->msg === null) { 
    
    } else if($this->msg[0] == 2 && isset($this->form)){
         $formularz = $this->form;
         $formularz->prepare();
         
         echo $this->form()->openTag($formularz);
         echo '<div class="alert alert-warning"><p>'.$this->msg[1].'</p>';
         echo '<p class="text-right">'.$this->formSubmit($form->get('submity')).' '.$this->formSubmit($form->get('submitc')).'</p>';
         echo '</div>';
         echo $this->form()->closeTag($formularz);
    } else if($msg[0] == 1){
        echo '<div class="alert alert-success">'.$msg[1].'</div>';
    } else {
        echo '<div class="alert alert-danger">'.$msg[1].'</div>';
    }

?>
 
