<?php

 $title = 'Mój profil';
 $this->headTitle($title);
 $user = $this->identity();

 if($user->poziom == 2){
    $poziomUzytkownikaStyl = 'danger';
    $poziomUzytkownikaNapis = 'ADMINISTRATOR';
 }
 else if($user->poziom == 1){
    $poziomUzytkownikaStyl = 'success';
    $poziomUzytkownikaNapis = 'LEKARZ';
 }
 else {
    $poziomUzytkownikaStyl = 'info';
    $poziomUzytkownikaNapis = 'PACJENT';
 }
 ?>

<div class="row">
  <div class="col-md-2 col-md-offset-2 text-center well well-sm">
  <span style="font-size: 85px;" class="glyphicon glyphicon-user alert alert-<?php echo $user->plec === 'M' ? 'info' : 'danger'; ?>"></span>
  <p><span style="padding: 9px" class="alert alert-<?php echo $poziomUzytkownikaStyl; ?>"><?php echo $poziomUzytkownikaNapis; ?></span></p>
  </div>
  <div class="col-md-6 well">
  <?php 
  if($user->aktywny != 1){ 
    echo '<p><span href="" title="" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-exclamation-sign"></span> Konto oczekuje na aktywację. Prosimy zgłosić się do naszej przychodni.</span></p>';
  }
  
  echo '<h3 style="margin-top: 0;">'.$this->escapeHtml($user->imie . ' ' . $user->nazwisko).' <a href="" title="" class="btn btn-warning btn-xs">Edytuj</a></h3>
  <dl class="dl-horizontal">';
  echo '<dt><span>PESEL</span></dt><dd> '.$this->escapeHtml($user->pesel).'</dd>';
  echo '<dt><span>Data urodzenia</span></dt><dd> '.$this->escapeHtml($user->data_ur).'</dd>';
  echo '<dt><span>Adres</span></dt><dd> '.$this->escapeHtml($user->adres).'</dd>';
  echo '<dt><span>E-Mail</span></dt><dd> '.$this->escapeHtml($user->email).'</dd>';
  if(!empty($user->telefon)) echo '<dt><span>Telefon</span></dt><dd> '.$this->escapeHtml($user->telefon).'</dd>';   
  
 
 ?>
  </dl>


  
  </div>
</div>