
<div class="jumbotron">
    <h1>Witaj w <span class="niebieski">Wirtualnej Przychodni</span></h1>
    <p>Prawdą jest, iż dokończenie aktualnych projektów wymaga niezwykłej precyzji w tym zakresie wymaga sprecyzowania i koledzy, konsultacja z dotychczasowymi zasadami dalszych poczynań. Nie chcę państwu niczego sugerować, ale zawiązanie koalicji rozszerza nam horyzonty form działalności zabezpiecza udział szerokiej grupie w określaniu modelu rozwoju. </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Kadra medyczna</h3>
            </div>
            <div class="panel-body">
                <p>Sprawdź w jakich godzinach przyjmują lekarze w naszej przychodni i wybierz sobie najdogodniejszy termin - łatwo i wygodnie!</p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('home') ?>" target="_blank">Znajdź lekarza &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Rejestracja</h3>
            </div>
            <div class="panel-body">
                <p>Nie masz jeszcze konta? Nie szkodzi! W klika minut zarejestrujesz się w naszym systemie. Wszystko bezproblemowo i oczywiście bezpłatnie! </p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('home') ?>" target="_blank">Zarejestruj się &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Pomoc</h3>
            </div>
            <div class="panel-body">
                <p>Masz problem z poruszaniem się po serwisie? A może po prostu potrzebujesz dodatkowych informacji? Zapraszamy do kontaktu z nami drogą telefoniczną lub poprzez e-mail!</p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('kontakt') ?>">Skontaktuj się z nami &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
